apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homedns.fullname" . }}
  labels:
    {{- include "homedns.labels" . | nindent 4 }}
data:
  Corefile: |
    {{- include "homedns.corefile" . | nindent 4 }}
